### PR TITLE
fix: support both https and ssh urls

### PR DESCRIPTION
**Pull request by spenrose**

### CODE REVIEW

**Comment by ciehanski** [comment]
Hello!

Thanks for the PR. You're right, this whole `M.get_remote_username()` function needs to be updated to support SSH URLs as well as git services running on custom ports and custom domains. I ran into some issues testing your regex string, but I came up with the following approach:

```lua
-- @return string
function M.get_remote_username()
  local username = ""
  if M.is_git_dir() then
    local remote_origin = fn.system("git remote get-url origin | tr -d '\n'")

    local user_repo
    if remote_origin:find("http") then
      -- http(s)
      user_repo = remote_origin:match("[^/]+/[^/]*$")
    else
      -- ssh
      user_repo = remote_origin:match("(?:[:/])([^:/]+/[^/]+)$")
    end

    username = user_repo:match("^[^/]+")
  end
  return username
end
```

**Comment by spenrose** [comment]
@ciehanski OK, yeah feel free to use yours. I was just trying to use the plugin and was having issues because I use ssh urls and not https. I should of probably wrote some tests to make sure mine worked in all the cases.

**Comment by ciehanski** [comment]
No problem, I appreciate you taking the time to submit a PR. Does the updated version above work for you on your SSH repos? If so, you can submit it in a commit and I'll push into `main`.

**Comment by spenrose** [comment]
@ciehanski Updated with your code. It works on my machine with ssh urls!

**Review by ciehanski — CHANGES_REQUESTED** [review]
Lastly, can you update
`user_repo = remote_origin:match("(?:[:/])([^:/]+/[^/]+)$")`
to
`user_repo = remote_origin:match("[:/]([^:/]+/[^/]+)$")`
and test that out for me?

I did some further testing on my side and this regex is more in line with Lua's pattern matching.

**Comment by spenrose** [comment]
@ciehanski  Updated and still working with ssh urls.

**Review by ciehanski — APPROVED** [review]

**Pull request merged**
